crab resubmit -d crab_projects/crab_SkimB4Mu_2023eraC-v3_stream0_Mini
crab resubmit -d crab_projects/crab_SkimB4Mu_2023eraC-v3_stream1_Mini
crab resubmit -d crab_projects/crab_SkimB4Mu_2023eraC-v3_stream2_Mini
crab resubmit -d crab_projects/crab_SkimB4Mu_2023eraC-v3_stream3_Mini
crab resubmit -d crab_projects/crab_SkimB4Mu_2023eraC-v3_stream4_Mini
crab resubmit -d crab_projects/crab_SkimB4Mu_2023eraC-v3_stream5_Mini
crab resubmit -d crab_projects/crab_SkimB4Mu_2023eraC-v3_stream6_Mini
crab resubmit -d crab_projects/crab_SkimB4Mu_2023eraC-v3_stream7_Mini
