crab resubmit -d crab_projects/crab_SkimB4Mu_2023eraC-v2_stream0_Mini
crab resubmit -d crab_projects/crab_SkimB4Mu_2023eraC-v2_stream1_Mini
crab resubmit -d crab_projects/crab_SkimB4Mu_2023eraC-v2_stream2_Mini
crab resubmit -d crab_projects/crab_SkimB4Mu_2023eraC-v2_stream3_Mini
crab resubmit -d crab_projects/crab_SkimB4Mu_2023eraC-v2_stream4_Mini
crab resubmit -d crab_projects/crab_SkimB4Mu_2023eraC-v2_stream5_Mini
crab resubmit -d crab_projects/crab_SkimB4Mu_2023eraC-v2_stream6_Mini
crab resubmit -d crab_projects/crab_SkimB4Mu_2023eraC-v2_stream7_Mini
