crab report -d crab_projects/crab_SkimB4Mu_2022eraG_stream0_Mini
crab report -d crab_projects/crab_SkimB4Mu_2022eraG_stream1_Mini
crab report -d crab_projects/crab_SkimB4Mu_2022eraG_stream2_Mini
crab report -d crab_projects/crab_SkimB4Mu_2022eraG_stream3_Mini
crab report -d crab_projects/crab_SkimB4Mu_2022eraG_stream4_Mini
crab report -d crab_projects/crab_SkimB4Mu_2022eraG_stream5_Mini
crab report -d crab_projects/crab_SkimB4Mu_2022eraG_stream6_Mini
crab report -d crab_projects/crab_SkimB4Mu_2022eraG_stream7_Mini
