crab report -d crab_projects/crab_SkimB4Mu_2022eraF_stream0_Mini
crab report -d crab_projects/crab_SkimB4Mu_2022eraF_stream1_Mini
crab report -d crab_projects/crab_SkimB4Mu_2022eraF_stream2_Mini
crab report -d crab_projects/crab_SkimB4Mu_2022eraF_stream3_Mini
crab report -d crab_projects/crab_SkimB4Mu_2022eraF_stream4_Mini
crab report -d crab_projects/crab_SkimB4Mu_2022eraF_stream5_Mini
crab report -d crab_projects/crab_SkimB4Mu_2022eraF_stream6_Mini
crab report -d crab_projects/crab_SkimB4Mu_2022eraF_stream7_Mini
