crab resubmit -d crab_projects/crab_SkimB4Mu_2023eraD-v1_stream0_Mini
crab resubmit -d crab_projects/crab_SkimB4Mu_2023eraD-v1_stream1_Mini
crab resubmit -d crab_projects/crab_SkimB4Mu_2023eraD-v1_stream2_Mini
crab resubmit -d crab_projects/crab_SkimB4Mu_2023eraD-v1_stream3_Mini
crab resubmit -d crab_projects/crab_SkimB4Mu_2023eraD-v1_stream4_Mini
crab resubmit -d crab_projects/crab_SkimB4Mu_2023eraD-v1_stream5_Mini
crab resubmit -d crab_projects/crab_SkimB4Mu_2023eraD-v1_stream6_Mini
crab resubmit -d crab_projects/crab_SkimB4Mu_2023eraD-v1_stream7_Mini
